"""add_api_keys_table

Revision ID: d19591ec8c45
Revises: 365ffc1d6ea0
Create Date: 2025-11-22 07:53:26.199724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19591ec8c45'
down_revision: Union[str, None] = '365ffc1d6ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.alter_column('oauth_tokens', 'token_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_comment='令牌类型',
               existing_nullable=False)
    op.alter_column('plugin_api_keys', 'user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('users', 'trust_level',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='用户信任等级',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='账号是否激活',
               existing_nullable=False)
    op.alter_column('users', 'is_silenced',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='是否被禁言',
               existing_nullable=False)
    op.drop_constraint('users_oauth_id_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_oauth_id', table_name='users')
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.create_index('ix_users_oauth_id', 'users', ['oauth_id'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_oauth_id_key', 'users', ['oauth_id'])
    op.alter_column('users', 'is_silenced',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='是否被禁言',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='账号是否激活',
               existing_nullable=False)
    op.alter_column('users', 'trust_level',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='用户信任等级',
               existing_nullable=False)
    op.alter_column('plugin_api_keys', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'token_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'bearer'::character varying"),
               existing_comment='令牌类型',
               existing_nullable=False)
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
